# Generated by Django 4.2.6 on 2023-10-19 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="phone",
            new_name="password",
        ),
    ]
