# Generated by Django 4.2.6 on 2023-10-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_rename_phone_registration_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="password",
            field=models.EmailField(max_length=254),
        ),
    ]
