# Generated by Django 4.2.6 on 2023-10-18 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloudpacer", "0002_remove_founder_image_remove_manager_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="image",
        ),
    ]
