# Generated by Django 4.2.6 on 2023-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloudpacer", "0003_remove_employee_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="professor",
            fields=[
                ("professor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("gender", models.CharField()),
                ("address", models.TextField(max_length=100)),
                ("contact_no", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("salary", models.IntegerField()),
                ("prof_course", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Founder",
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
