# Generated by Django 4.2.6 on 2023-10-19 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloudpacer", "0005_employee_founder_manager_delete_professor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Founder",
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
