# Generated by Django 4.2.6 on 2023-10-19 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloudpacer", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
